/* Shared presentation lifecycle. Keeps existing forms, commands and storage authoritative. */
(function(root,factory){'use strict';const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MasarifiInteraction=api;})(typeof window==='undefined'?globalThis:window,function(root){'use strict';
const doc=root.document,ignored=new Set(['serviceCompose','v6AssistantForm','chatForm','directorySearch','v7AccountFilters','unlockForm']),pageForms=new Set(['prefsForm','v5Settings','v6Prefs','v17GeneralPrefs','v7HomePrefs','v7PrimaryAccountForm','v85SubscriptionRequest','settingsForm','billingForm','supportForm']);
function fingerprint(form){return JSON.stringify(Array.from(form?.elements||[]).filter(n=>n&&n.tagName!=='BUTTON'&&!['submit','button','reset','image'].includes(n.type)).map((n,index)=>{let value;if(n.type==='file')value=Array.from(n.files||[]).map(f=>[f.name,f.size,f.lastModified,f.type]);else if(n.tagName==='SELECT'&&n.multiple)value=Array.from(n.selectedOptions||[]).map(o=>o.value);else if(n.type==='checkbox'||n.type==='radio')value=[!!n.checked,String(n.value??'')];else value=String(n.value??'');return[index,String(n.name||n.id||''),n.type||n.tagName,value];}));}
function managedForm(form){if(!form||ignored.has(form.id)||form.dataset?.interactionIgnore==='true'||form.dataset?.commandForm==='search')return false;return pageForms.has(form.id)||['mainForm','auxForm'].includes(form.id)||!!form.closest?.('dialog');}
function revealDelta(field,bounds,padding=12){if(field.top>=bounds.top&&field.bottom<=bounds.bottom)return 0;const available=Math.max(0,bounds.bottom-bounds.top-padding*2);if(field.bottom-field.top>available)return field.top-bounds.top-padding;if(field.top<bounds.top+padding)return field.top-bounds.top-padding;if(field.bottom>bounds.bottom-padding)return field.bottom-bounds.bottom+padding;return 0;}
const words={ar:{discard:'توجد تغييرات غير محفوظة. هل تريد تجاهلها والمتابعة؟',busy:'جارٍ الحفظ. انتظر اكتمال العملية.'},tr:{discard:'Kaydedilmemiş değişiklikler var. Değişiklikleri atıp devam edilsin mi?',busy:'Kaydediliyor. İşlemin tamamlanmasını bekleyin.'},en:{discard:'You have unsaved changes. Discard them and continue?',busy:'Saving. Please wait for this operation to finish.'},ku:{discard:'Guherînên nehatine tomarkirin hene. Wan biavêjî û bidomînî?',busy:'Tê tomarkirin. Li benda qedandina vê karê bimîne.'},fr:{discard:'Des modifications ne sont pas enregistrées. Les abandonner et continuer ?',busy:'Enregistrement en cours. Attendez la fin de l’opération.'}};
function controller(options={}){const records=new WeakMap(),allForms=scope=>[...(scope?.tagName==='FORM'?[scope]:[]),...Array.from(scope?.querySelectorAll?.('form')||[])],forms=scope=>allForms(scope).filter(managedForm),lang=()=>words[options.language?.()]||words.en;
 const track=form=>{if(managedForm(form)&&!records.has(form))records.set(form,{baseline:fingerprint(form),touched:false,settled:false});return records.get(form);};
 const busy=scope=>scope?.dataset?.busy==='1'||scope?.getAttribute?.('aria-busy')==='true'||allForms(scope).some(f=>f.dataset?.busy==='1'||f.getAttribute?.('aria-busy')==='true'||Number(f.photoEditor?.busy)>0);
 const dirtyForms=scope=>forms(scope).filter(f=>{const r=track(f);const value=fingerprint(f);return r&&r.baseline!==value&&r.approved!==value;});
 // Synchronous callers fail closed. Async callers own the decision and recheck the exact draft.
 const check=scope=>{if(busy(scope)){options.onBusy?.(lang().busy);return false;}return !dirtyForms(scope).length||options.confirm?.(lang().discard)===true;};
 const request=async scope=>{const scopes=Array.isArray(scope)?scope:[scope];if(scopes.some(busy)){options.onBusy?.(lang().busy);return false;}const snapshots=[...new Set(scopes.flatMap(dirtyForms))].map(form=>({form,value:fingerprint(form)}));if(!snapshots.length)return true;const accepted=await (options.confirmAsync?.(lang().discard)??options.confirm?.(lang().discard)??false);const allowed=accepted===true&&!scopes.some(busy)&&snapshots.every(({form,value})=>form.isConnected!==false&&fingerprint(form)===value);if(allowed)for(const {form,value} of snapshots)records.get(form).approved=value;return allowed;};
 return{track,busy,canClose:check,canLeave:check,requestClose:request,requestLeave:request,discardApproval(scope){for(const item of Array.isArray(scope)?scope:[scope])for(const form of forms(item)){const r=track(form);if(r)r.approved=null;}},touch(form){const r=track(form);if(r){r.touched=true;r.approved=null;}},settle(form){const r=track(form);if(r&&!r.settled){if(!r.touched)r.baseline=fingerprint(form);r.settled=true;}},markSaved(form){const r=track(form);if(r){r.baseline=fingerprint(form);r.approved=null;r.touched=false;r.settled=true;}if(form?.dataset){delete form.dataset.mxDirty;delete form.dataset.interactionDirty;}},dirty(form){const r=track(form);return !!r&&r.baseline!==fingerprint(form);}};
}
const state=controller({language:()=>root.App?.prefs?.language||root.MasarifiAdminBridge?.getLocale?.()||doc?.documentElement?.lang||'en',confirmAsync:text=>api.confirm(text),onBusy:text=>root.App?.toast?.(text)});
function normalizeNumericControls(scope=doc,language=doc?.documentElement?.lang||'en'){const base=String(language).split('-')[0],locale=(['ar','en','tr','fr'].includes(base)?base:'en')+'-u-nu-latn';for(const field of scope?.querySelectorAll?.('input[type=date],input[type=datetime-local],input[type=time],input[type=month],input[type=week],input[type=number],input[inputmode=decimal],input[inputmode=numeric]')||[]){if(field.type==='password')continue;if(field.getAttribute('lang')!==locale)field.setAttribute('lang',locale);if(field.getAttribute('dir')!=='ltr')field.setAttribute('dir','ltr');}}
const api={...state,fingerprint,managedForm,revealDelta,controller,normalizeNumericControls,prepare:()=>{},refresh:()=>{}};
if(!doc||!root.HTMLDialogElement)return api;
const confirmLabels={ar:['تغييرات غير محفوظة','الاحتفاظ بالتغييرات','تجاهل والمتابعة'],tr:['Kaydedilmemiş değişiklikler','Düzenlemeye devam et','At ve devam et'],en:['Unsaved changes','Keep editing','Discard and continue'],fr:['Modifications non enregistrées','Continuer à modifier','Abandonner et continuer'],ku:['Guherînên nehatine tomarkirin','Berdewam bike','Biavêje û bidomîne']};
let confirmation=null;
function confirmStamp(){return JSON.stringify([root.App?.locked,root.App?.page,root.V6?.settingsSection,root.V5?.lockGeneration,root.Online?.user?.id,root.Online?.authEpoch,root.Online?.modeEpoch,root.Online?.Workspace?.context,root.MasarifiAdminBridge?.getUserId?.()]);}
api.confirm=function(message,options={}){if(confirmation||root.App?.locked)return Promise.resolve(false);const labels=confirmLabels[root.App?.prefs?.language||root.MasarifiAdminBridge?.getLocale?.()||doc.documentElement.lang]||confirmLabels.en,d=doc.createElement('dialog'),stamp=confirmStamp(),background=backgroundMarker(),opener=doc.activeElement;
 d.id='masarifiConfirm';d.className='interaction-confirm';d.dataset.interactionTransient='true';d.setAttribute('role','alertdialog');d.setAttribute('aria-modal','true');d.setAttribute('aria-labelledby','masarifiConfirmTitle');d.setAttribute('aria-describedby','masarifiConfirmDescription');
 const head=doc.createElement('header');head.className='dialog-head';const title=doc.createElement('h2');title.id='masarifiConfirmTitle';title.textContent=options.title||labels[0];head.append(title);
 const body=doc.createElement('div');body.className='dialog-body';const text=doc.createElement('p');text.id='masarifiConfirmDescription';text.textContent=String(message);body.append(text);
 const footer=doc.createElement('footer');footer.className='dialog-actions';const keep=doc.createElement('button'),discard=doc.createElement('button');keep.type=discard.type='button';keep.textContent=options.cancelLabel||labels[1];discard.textContent=options.confirmLabel||labels[2];discard.className='interaction-discard';keep.autofocus=true;footer.append(keep,discard);d.append(head,body,footer);doc.body.append(d);
 return new Promise(resolve=>{let settled=false;const finish=accepted=>{if(settled)return;settled=true;const current=stamp===confirmStamp()&&background===backgroundMarker()&&d.isConnected;confirmation=null;if(d.open)d.close();d.remove();resolve(accepted===true&&current);if(current)microtask(()=>safeFocus(opener));};confirmation={dialog:d,finish};keep.addEventListener('click',()=>finish(false));discard.addEventListener('click',()=>finish(true));d.addEventListener('cancel',event=>{event.preventDefault();finish(false);});d.addEventListener('close',()=>finish(false));d.addEventListener('click',event=>{if(event.target!==d)return;const r=d.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)finish(false);});try{d.showModal();keep.focus({preventScroll:true});}catch{finish(false);}});
};
api.cancelConfirm=()=>{if(!confirmation)return false;confirmation.finish(false);return true;};
api.isConfirmOpen=()=>!!confirmation;
root.addEventListener('v6:locked',()=>api.cancelConfirm());root.addEventListener('pagehide',()=>api.cancelConfirm());
const seen=new WeakMap(),settleForms=new WeakSet();let scheduled=false,lastOpener=null,openSerial=0,navigationGeneration=0;
const microtask=fn=>root.queueMicrotask?root.queueMicrotask(fn):Promise.resolve().then(fn);
function register(form){if(!managedForm(form))return;state.track(form);if(!settleForms.has(form)){settleForms.add(form);microtask(()=>state.settle(form));}}
function direct(parent,selector){return Array.from(parent.children||[]).find(n=>n.matches(selector))||null;}
function structureForm(form){if(!form||direct(form,'.dialog-form-scroll'))return;let footer=direct(form,'.dialog-actions');if(!footer){const tail=form.lastElementChild;if(tail?.matches('.row,.dialog-footer,.form-actions')&&tail.querySelector('button[type=submit],input[type=submit]')){footer=tail;footer.classList.add('dialog-actions');}}if(!footer)return;const scroll=doc.createElement('div');scroll.className='dialog-form-scroll';for(const n of Array.from(form.childNodes))if(n!==footer)scroll.append(n);form.insertBefore(scroll,footer);form.classList.add('dialog-form');}
function prepare(d){if(!d?.isConnected)return;d.classList.add('interaction-dialog');let body=direct(d,'.dialog-body,.mx-body,.np-body,.command-content,.interaction-body,.v17-scan-body');const heading=direct(d,'.dialog-head,.mx-heading,.np-head,.command-heading,.sheet-heading,.v17-scan-head'),headTitle=heading?.querySelector('h1,h2,h3');
 if(headTitle&&!headTitle.id){headTitle.id='interaction-title-'+(d.id||Math.random().toString(36).slice(2));}if(headTitle&&!d.getAttribute('aria-labelledby'))d.setAttribute('aria-labelledby',headTitle.id);if(headTitle&&!headTitle.hasAttribute('tabindex'))headTitle.tabIndex=-1;
 if(!body&&heading){body=doc.createElement('div');body.className='interaction-body';const footer=direct(d,'.dialog-actions,.np-footer,.mx-actions'),grip=direct(d,'.sheet-grip');for(const n of Array.from(d.childNodes))if(n!==heading&&n!==footer&&n!==grip)body.append(n);d.insertBefore(body,footer||null);}
 if(body){const footer=direct(body,'.dialog-actions,.np-footer,.mx-actions');if(footer&&!footer.closest('form'))d.append(footer);const aiFooter=body.querySelector('[data-ai-action=send]')?.closest('.row');if(aiFooter&&!aiFooter.closest('form')){aiFooter.classList.add('dialog-actions');d.append(aiFooter);}const form=direct(body,'form');if(form){structureForm(form);if(direct(form,'.dialog-form-scroll')){d.dataset.interactionLayout='form';body.classList.add('interaction-form-body');form.classList.add('dialog-form');}else d.dataset.interactionLayout='body';}else d.dataset.interactionLayout='body';}
 else d.dataset.interactionLayout='plain';
 for(const f of d.querySelectorAll('form'))register(f);const record=seen.get(d);if(d.open&&!record?.opened){seen.set(d,{opened:true,serial:++openSerial,opener:lastOpener?.isConnected?lastOpener:doc.activeElement,scrollX:root.scrollX||0,scrollY:root.scrollY||0,generation:navigationGeneration,page:root.App?.page,background:backgroundMarker()});lastOpener=null;}if(!d.open&&record?.opened){record.opened=false;restore(record);}
}
function backgroundMarker(){return (doc.getElementById('content')||doc.getElementById('screen')||doc.getElementById('adminRoot'))?.firstElementChild||null;}
function topDialog(){return Array.from(doc.querySelectorAll('dialog[open]')).sort((a,b)=>(seen.get(a)?.serial||0)-(seen.get(b)?.serial||0)).at(-1);}
function safeFocus(target){if(!target?.isConnected||target.disabled||target.closest('[hidden],[inert]')||target.closest('#shell[hidden],#lockScreen:not([hidden])'))return false;const top=topDialog();if(top&&!top.contains(target))return false;if(root.App?.locked&&!target.closest('#lockScreen'))return false;try{target.focus({preventScroll:true});return true;}catch{return false;}}
function restore(record){microtask(()=>{const samePage=record.generation===navigationGeneration&&record.page===root.App?.page&&record.background===backgroundMarker();if(!samePage)return;if(record.opener&&!safeFocus(record.opener)){const modal=topDialog();const target=modal?.querySelector('.dialog-head h2,.mx-heading h2,.command-heading h2,.np-head h2')||doc.querySelector('#content h1,#screen h1,#screen h2');safeFocus(target);}if(!doc.querySelector('dialog[open]')&&!root.App?.locked&&Math.abs((root.scrollY||0)-record.scrollY)>2)root.scrollTo?.({left:record.scrollX,top:record.scrollY,behavior:'instant'});});}
function reveal(target=doc.activeElement){if(!target?.matches?.('input:not([type=checkbox]):not([type=radio]):not([type=range]),textarea,select,[contenteditable=true]'))return;const d=target.closest('dialog');if(d){if(!d.open)return;const scroll=target.closest('.dialog-form-scroll,.dialog-body,.mx-body,.np-body,.command-content,.interaction-body,.v17-scan-body');if(!scroll||!scroll.contains(target))return;const delta=revealDelta(target.getBoundingClientRect(),scroll.getBoundingClientRect());if(Math.abs(delta)>1)scroll.scrollTop=Math.max(0,Math.min(scroll.scrollHeight-scroll.clientHeight,scroll.scrollTop+delta));}else if(doc.documentElement.dataset.keyboard==='true'){const viewport=root.MasarifiExperience?.viewport,top=viewport?.top||0,height=viewport?.height||root.innerHeight;const delta=revealDelta(target.getBoundingClientRect(),{top,bottom:top+height},18);if(Math.abs(delta)>1)root.scrollBy?.({top:delta,behavior:'instant'});}}
function refresh(){scheduled=false;normalizeNumericControls();for(const f of doc.querySelectorAll('form'))register(f);for(const d of doc.querySelectorAll('dialog'))prepare(d);reveal();}
function queue(){if(scheduled)return;scheduled=true;(root.requestAnimationFrame||((fn)=>setTimeout(fn,0)))(refresh);}
api.prepare=prepare;api.refresh=refresh;api.topDialog=topDialog;
const proto=root.HTMLDialogElement.prototype,show=proto.showModal;proto.showModal=function(){if(!this.open){lastOpener=doc.activeElement;prepare(this);const h=this.querySelector('.dialog-head h2,.np-head h2,.command-heading h2');if(h&&!this.querySelector('[autofocus]'))h.setAttribute('autofocus','');}const result=show.apply(this,arguments);prepare(this);queue();return result;};
doc.addEventListener('input',e=>{if(e.isTrusted!==false){const f=e.target.closest?.('form');if(f)state.touch(f);}},true);doc.addEventListener('change',e=>{if(e.isTrusted!==false){const f=e.target.closest?.('form');if(f)state.touch(f);}},true);
doc.addEventListener('focusin',()=>queue());doc.addEventListener('close',e=>{if(e.target?.tagName==='DIALOG'){const r=seen.get(e.target);if(r?.opened&&!e.target.open){r.opened=false;restore(r);}queue();}},true);
doc.addEventListener('cancel',e=>{const d=e.target;if(e.defaultPrevented||!d?.open||d.dataset.interactionTransient==='true'||['adminDialog','masarifiAdminOperations'].includes(d.id)||root.V6)return;e.preventDefault();state.requestClose(d).then(allowed=>{if(allowed&&d.open)d.close();});},true);
doc.addEventListener('invalid',e=>{const target=e.target;if(target?.closest?.('dialog[open]')){queue();}},true);
doc.addEventListener('masarifi:viewport',()=>queue());doc.addEventListener('masarifi:navigation',()=>{navigationGeneration++;const page=doc.getElementById('content')||doc.getElementById('screen');if(!page)return;page.classList.remove('interaction-page-arrive');(root.requestAnimationFrame||setTimeout)(()=>{if(!root.App?.locked&&!doc.querySelector('dialog[open]'))page.classList.add('interaction-page-arrive');});});
root.addEventListener('v6:locked',()=>{lastOpener=null;navigationGeneration++;});root.addEventListener('pageshow',()=>{root.MasarifiExperience?.paintViewport?.();queue();});
const observer=new MutationObserver(queue);observer.observe(doc.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open','aria-busy','data-busy']});refresh();
return api;
});

