importScripts('./badge-worker.js');
/* Cache only the static admin shell. API responses and private records never enter this cache. */
const RUNTIME_VERSION='7.14.0';
const ADMIN_CACHE_PREFIX='masarifi-admin-runtime:'+self.registration.scope+':',ADMIN_CACHE=ADMIN_CACHE_PREFIX+RUNTIME_VERSION+'-ab97b31b4386';
const ADMIN_STATIC_ENABLED=!new URL(self.location.href).pathname.endsWith('/admin/push-sw.js');
const ADMIN_FILES=['./','./index.html','./manifest.webmanifest','./icon-192.png','./icon-512.png','./admin-icon.svg','./notification-badge.png','./app-experience.js','./app-experience.css','./badge-worker.js'];
self.addEventListener('install',event=>{if(ADMIN_STATIC_ENABLED)event.waitUntil(caches.open(ADMIN_CACHE).then(cache=>cache.addAll(ADMIN_FILES)));});
self.addEventListener('activate',event=>event.waitUntil((async()=>{if(ADMIN_STATIC_ENABLED)for(const key of await caches.keys())if(key.startsWith(ADMIN_CACHE_PREFIX)&&key!==ADMIN_CACHE)await caches.delete(key);await self.clients.claim();})()));
self.addEventListener('fetch',event=>{if(!ADMIN_STATIC_ENABLED||event.request.method!=='GET')return;const url=new URL(event.request.url),scope=new URL(self.registration.scope);if(url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname))return;const relative='./'+url.pathname.slice(scope.pathname.length);if(!ADMIN_FILES.includes(relative))return;event.respondWith((async()=>{const cache=await caches.open(ADMIN_CACHE),hit=await cache.match(event.request,{ignoreSearch:true});return hit||fetch(event.request);})());});
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE')self.skipWaiting();});
const PUSH_PREFS='masarifi-admin-push-preferences';
const PUSH_IMAGE_ORIGIN='https://oxsrajzowlxydzgipquy.supabase.co';
let identityEpoch=0;
const identityURL=()=>new URL('__admin_push_identity',self.registration.scope).href;
const validId=id=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
function pushImage(value,expires){try{const u=new URL(value),id='[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';if(u.origin!==PUSH_IMAGE_ORIGIN||u.username||u.password||u.hash)return;if(!u.search&&new RegExp('^/storage/v1/object/public/masarifi-announcements/'+id+'[.](jpg|png|webp)$','i').test(u.pathname))return u.href;if(!Number.isFinite(Date.parse(expires))||Date.parse(expires)<=Date.now())return;const token=u.searchParams.get('token');if(u.searchParams.size===1&&token&&token.length<2048&&/^[A-Za-z0-9_.-]+$/.test(token)&&new RegExp('^/storage/v1/object/sign/masarifi-service/'+id+'/'+id+'/'+id+'[.](jpg|png|webp)$','i').test(u.pathname))return u.href;}catch{}}
self.addEventListener('message',event=>{if(event.data?.type!=='PUSH_ACCOUNT')return;const epoch=++identityEpoch;event.waitUntil((async()=>{const cache=await caches.open(PUSH_PREFS);if(epoch!==identityEpoch)return;await self.MasarifiBadge.account(event.data.userId||null);if(epoch!==identityEpoch)return;if(event.data.userId)await cache.put(identityURL(),new Response(String(event.data.userId)));else await cache.delete(identityURL());if(epoch!==identityEpoch)return;for(const notice of await self.registration.getNotifications())if(!event.data.userId||notice.data?.userId&&notice.data.userId!==event.data.userId)notice.close();})());});
async function sameRecipient(id,epoch){const cache=await caches.open(PUSH_PREFS),identity=await cache.match(identityURL());return !!identity&&(await identity.text())===id&&epoch===identityEpoch;}
self.addEventListener('push',event=>event.waitUntil((async()=>{const epoch=identityEpoch;let p;try{p=event.data?.json()}catch{return;}if(!p||!validId(p.id)||!['campaign','system'].includes(p.source||'campaign')||typeof p.title!=='string'||typeof p.body!=='string'||!Number.isFinite(Date.parse(p.expires_at))||Date.parse(p.expires_at)<=Date.now())return;if(!await sameRecipient(p.user_id,epoch))return;let fresh=true;try{fresh=await self.MasarifiBadge.push(p.user_id,p.id,p.source||'campaign',()=>sameRecipient(p.user_id,epoch),p);}catch{}if(!fresh||!await sameRecipient(p.user_id,epoch))return;await showPush(p.title.slice(0,180),{body:p.body.slice(0,2000),image:pushImage(p.image,p.image_expires_at),tag:'masarifi-admin-'+p.id,renotify:false,icon:new URL('icon-192.png',self.registration.scope).href,badge:new URL('notification-badge.png',self.registration.scope).href,data:{id:p.id,userId:p.user_id,source:p.source||'campaign'},dir:'auto',timestamp:Date.now(),silent:await hasForegroundWindow()});if(epoch!==identityEpoch){for(const n of await self.registration.getNotifications())if(n.data?.userId===p.user_id)n.close();}else await notifyWindows();})()));
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil((async()=>{const epoch=identityEpoch,data=event.notification.data||{},scope=new URL(self.registration.scope),combined=!!self.location?.href&&new URL(self.location.href).pathname.endsWith('/admin/push-sw.js'),entry=combined?new URL('../admin.html',scope):scope;if(!data.userId||!validId(data.id)||!['campaign','system'].includes(data.source)||!await sameRecipient(data.userId,epoch))return;const message={type:'OPEN_ADMIN_NOTIFICATIONS',id:data.id,source:data.source};const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});if(epoch!==identityEpoch)return;for(const client of clients){const url=new URL(client.url);if(url.origin===scope.origin&&(combined?url.pathname===entry.pathname:url.pathname.startsWith(scope.pathname))){client.postMessage(message);return client.focus();}}const url=new URL(entry.href);url.searchParams.set('notifications','1');url.searchParams.set('notice',data.id);url.searchParams.set('source',data.source);return self.clients.openWindow(url.href);})());});

async function notifyWindows(){const scope=new URL(self.registration.scope);for(const client of await self.clients.matchAll({type:'window',includeUncontrolled:false})){const url=new URL(client.url);if(url.origin===scope.origin&&url.pathname.startsWith(scope.pathname))client.postMessage({type:'MASARIFI_PUSH_RECEIVED'});}}

async function hasForegroundWindow(){const scope=new URL(self.registration.scope);return(await self.clients.matchAll({type:'window',includeUncontrolled:false})).some(c=>{const u=new URL(c.url);return u.origin===scope.origin&&u.pathname.startsWith(scope.pathname)&&c.visibilityState==='visible';});}
async function showPush(title,options){const epoch=identityEpoch;if(!await sameRecipient(options.data?.userId,epoch))return;try{await self.registration.showNotification(title,options);}catch(error){if(!options.image)throw error;if(!await sameRecipient(options.data?.userId,epoch))return;delete options.image;await self.registration.showNotification(title,options);}}
