importScripts('./badge-worker.js');
/* Cache only the static admin shell. API responses and private records never enter this cache. */
const RUNTIME_VERSION='8.7.0';
const ADMIN_CACHE_PREFIX='masarifi-admin-runtime:'+self.registration.scope+':',ADMIN_CACHE=ADMIN_CACHE_PREFIX+RUNTIME_VERSION+'-f3185b7d3322';
const ADMIN_STATIC_ENABLED=!new URL(self.location.href).pathname.endsWith('/admin/push-sw.js');
const ADMIN_FILES=["./","./index.html","./manifest.webmanifest","./icon-192.png","./icon-512.png","./admin-icon.svg","./notification-badge.png","./app-experience.js","./app-experience.css","./badge-worker.js","./notification-preferences.js","./notification-preferences.css","./app.css","./vendors.js","./admin-command.js","./admin-command.css","./interaction-shell.js","./interaction-shell.css","./user-usage.js","./user-usage.css","./app-locale.js","./manifest.ar.webmanifest","./manifest.tr.webmanifest","./manifest.en.webmanifest","./manifest.fr.webmanifest","./theme-polish.css","./release.json"];
self.addEventListener('install',event=>{if(ADMIN_STATIC_ENABLED)event.waitUntil(caches.open(ADMIN_CACHE).then(cache=>cache.addAll(ADMIN_FILES.map(file=>new Request(new URL(file,self.registration.scope),{cache:'reload'})))));});
self.addEventListener('activate',event=>event.waitUntil((async()=>{if(ADMIN_STATIC_ENABLED)for(const key of await caches.keys())if(key.startsWith(ADMIN_CACHE_PREFIX)&&key!==ADMIN_CACHE)await caches.delete(key);await self.clients.claim();})()));
self.addEventListener('fetch',event=>{if(!ADMIN_STATIC_ENABLED||event.request.method!=='GET')return;const url=new URL(event.request.url),scope=new URL(self.registration.scope);if(url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname))return;const relative='./'+url.pathname.slice(scope.pathname.length);if(!ADMIN_FILES.includes(relative))return;event.respondWith((async()=>{const cache=await caches.open(ADMIN_CACHE),hit=await cache.match(event.request,{ignoreSearch:true});return hit||fetch(event.request);})());});
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE')self.skipWaiting();});
const PUSH_PREFS='masarifi-admin-push-preferences';
const PUSH_IMAGE_ORIGIN='https://oxsrajzowlxydzgipquy.supabase.co';
let identityEpoch=0,identityQueue=Promise.resolve(),pushQueue=Promise.resolve(),settingsQueue=Promise.resolve();
const identityURL=()=>new URL('__admin_push_identity',self.registration.scope).href;
const validId=id=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
function pushImage(value,expires){try{const u=new URL(value),id='[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';if(u.origin!==PUSH_IMAGE_ORIGIN||u.username||u.password||u.hash)return;if(!u.search&&new RegExp('^/storage/v1/object/public/masarifi-announcements/'+id+'[.](jpg|png|webp)$','i').test(u.pathname))return u.href;if(!Number.isFinite(Date.parse(expires))||Date.parse(expires)<=Date.now())return;const token=u.searchParams.get('token');if(u.searchParams.size===1&&token&&token.length<2048&&/^[A-Za-z0-9_.-]+$/.test(token)&&new RegExp('^/storage/v1/object/sign/masarifi-service/'+id+'/'+id+'/'+id+'[.](jpg|png|webp)$','i').test(u.pathname))return u.href;}catch{}}
self.addEventListener('message',event=>{if(event.data?.type!=='PUSH_ACCOUNT')return;const epoch=++identityEpoch;const task=identityQueue.catch(()=>{}).then(async()=>{const cache=await caches.open(PUSH_PREFS);if(epoch!==identityEpoch)return;await self.MasarifiBadge.account(event.data.userId||null);if(epoch!==identityEpoch)return;if(event.data.userId)await cache.put(identityURL(),new Response(String(event.data.userId)));else await cache.delete(identityURL());if(epoch!==identityEpoch)return;for(const notice of await self.registration.getNotifications())if(!event.data.userId||notice.data?.userId&&notice.data.userId!==event.data.userId)notice.close();});identityQueue=task;event.waitUntil(task);});
async function sameRecipient(id,epoch){const cache=await caches.open(PUSH_PREFS),identity=await cache.match(identityURL());return !!identity&&(await identity.text())===id&&epoch===identityEpoch;}
const notificationSettingsURL=()=>new URL('__notification_settings',self.registration.scope).href;
async function notificationSettings(userId){try{const cache=await caches.open(PUSH_PREFS),hit=await cache.match(notificationSettingsURL()),saved=hit?await hit.json():null;return self.MasarifiNotifications.settings(saved?.userId===userId?saved:null);}catch{return self.MasarifiNotifications.settings(null);}}
self.addEventListener('message',event=>{if(event.data?.type!=='NOTIFICATION_SETTINGS')return;const epoch=identityEpoch,d=event.data;const task=settingsQueue.catch(()=>{}).then(async()=>{await identityQueue.catch(()=>{});if(!await sameRecipient(d.userId,epoch))return;const settings=self.MasarifiNotifications.settings(d),cache=await caches.open(PUSH_PREFS);if(!await sameRecipient(d.userId,epoch))return;await cache.put(notificationSettingsURL(),new Response(JSON.stringify({userId:d.userId,...settings})));});settingsQueue=task;event.waitUntil(task);});
self.addEventListener('push',event=>{const task=pushQueue.catch(()=>{}).then(async()=>{
 const epoch=identityEpoch,p=self.MasarifiNotifications.parse(event.data);if(!p||!await sameRecipient(p.user_id,epoch))return;
 await settingsQueue.catch(()=>{});if(!await sameRecipient(p.user_id,epoch))return;const settings=await notificationSettings(p.user_id),prefs=settings.preferences;
 if(!prefs.push||prefs.categories[p.category]?.push===false){await notifyWindows();return;}
 const badgePayload={...p,badge_enabled:p.badge_enabled!==false&&prefs.badge};
 let fresh=true;try{fresh=await self.MasarifiBadge.push(p.user_id,p.id,p.source,()=>sameRecipient(p.user_id,epoch),badgePayload);}catch{}if(!fresh||!await sameRecipient(p.user_id,epoch))return;
 const shown=await showPush(p.title.slice(0,180),{body:p.body.slice(0,2000),image:prefs.images?pushImage(p.image,p.image_expires_at):undefined,tag:'masarifi-admin-'+p.source+'-'+p.id,renotify:false,icon:new URL('icon-192.png',self.registration.scope).href,badge:new URL('notification-badge.png',self.registration.scope).href,data:{id:p.id,userId:p.user_id,source:p.source,expiresAt:p.expires_at},dir:'auto',timestamp:Date.now(),silent:p.silent===true||!prefs.sound||self.MasarifiNotifications.isQuiet(settings.quietHours)||await hasForegroundWindow()});
 if(shown)await self.MasarifiBadge.delivered(p.user_id,p.id,p.source).catch(()=>{});
 if(epoch!==identityEpoch){for(const n of await self.registration.getNotifications())if(n.data?.userId===p.user_id)n.close();}else await notifyWindows();
 });pushQueue=task;event.waitUntil(task);});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil((async()=>{const epoch=identityEpoch,data=event.notification.data||{},scope=new URL(self.registration.scope),combined=!!self.location?.href&&new URL(self.location.href).pathname.endsWith('/admin/push-sw.js'),entry=combined?new URL('../admin.html',scope):scope;if(!data.userId||!validId(data.id)||!['campaign','system'].includes(data.source)||!await sameRecipient(data.userId,epoch))return;const message={type:'OPEN_ADMIN_NOTIFICATIONS',id:data.id,source:data.source};const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});if(epoch!==identityEpoch)return;for(const client of clients){const url=new URL(client.url);if(url.origin===scope.origin&&(combined?url.pathname===entry.pathname:url.pathname.startsWith(scope.pathname))){client.postMessage(message);return client.focus();}}const url=new URL(entry.href);url.searchParams.set('notifications','1');url.searchParams.set('notice',data.id);url.searchParams.set('source',data.source);return self.clients.openWindow(url.href);})());});

function isAdminWindow(client){const scope=new URL(self.registration.scope),url=new URL(client.url);return url.origin===scope.origin&&(ADMIN_STATIC_ENABLED?url.pathname.startsWith(scope.pathname):url.pathname===new URL('../admin.html',scope).pathname);}
async function notifyWindows(){for(const client of await self.clients.matchAll({type:'window',includeUncontrolled:!ADMIN_STATIC_ENABLED}))if(isAdminWindow(client))client.postMessage({type:'MASARIFI_PUSH_RECEIVED'});}
async function hasForegroundWindow(){return(await self.clients.matchAll({type:'window',includeUncontrolled:!ADMIN_STATIC_ENABLED})).some(client=>isAdminWindow(client)&&client.visibilityState==='visible');}
async function showPush(title,options){const epoch=identityEpoch,current=async()=>await sameRecipient(options.data?.userId,epoch)&&Date.parse(options.data?.expiresAt)>Date.now();if(!await current())return false;try{await self.registration.showNotification(title,options);}catch(error){if(!options.image)throw error;if(!await current())return false;delete options.image;await self.registration.showNotification(title,options);}return true;}
