importScripts('./badge-worker.js');
/* Independent admin push worker: no fetch handler and no private page cache. */
const RUNTIME_VERSION='7.11.0';
self.addEventListener('activate',event=>event.waitUntil(self.clients.claim()));
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE')self.skipWaiting();});
const PUSH_PREFS='masarifi-admin-push-preferences';
const PUSH_IMAGE_ORIGIN='https://oxsrajzowlxydzgipquy.supabase.co';
let identityEpoch=0;
const identityURL=()=>new URL('__admin_push_identity',self.registration.scope).href;
const validId=id=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
function publicImage(value){try{const u=new URL(value);return u.origin===PUSH_IMAGE_ORIGIN&&!u.search&&!u.hash&&/^\/storage\/v1\/object\/public\/masarifi-announcements\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$/i.test(u.pathname)?u.href:undefined;}catch{return undefined;}}
self.addEventListener('message',event=>{if(event.data?.type!=='PUSH_ACCOUNT')return;const epoch=++identityEpoch;event.waitUntil((async()=>{const cache=await caches.open(PUSH_PREFS);if(epoch!==identityEpoch)return;await self.MasarifiBadge.account(event.data.userId||null);if(epoch!==identityEpoch)return;if(event.data.userId)await cache.put(identityURL(),new Response(String(event.data.userId)));else{await cache.delete(identityURL());for(const notice of await self.registration.getNotifications())notice.close();}})());});
async function sameRecipient(id,epoch){const cache=await caches.open(PUSH_PREFS),identity=await cache.match(identityURL());return !!identity&&(await identity.text())===id&&epoch===identityEpoch;}
self.addEventListener('push',event=>event.waitUntil((async()=>{const epoch=identityEpoch;let p;try{p=event.data?.json()}catch{return;}if(!p||!validId(p.id)||!['campaign','system'].includes(p.source||'campaign')||typeof p.title!=='string'||typeof p.body!=='string'||!Number.isFinite(Date.parse(p.expires_at))||Date.parse(p.expires_at)<=Date.now())return;if(!await sameRecipient(p.user_id,epoch))return;await self.MasarifiBadge.push(p.user_id,p.id,p.source||'campaign',()=>sameRecipient(p.user_id,epoch));if(!await sameRecipient(p.user_id,epoch))return;await self.registration.showNotification(p.title.slice(0,180),{body:p.body.slice(0,2000),image:publicImage(p.image),tag:'masarifi-admin-'+p.id,renotify:false,icon:new URL('icon-192.png',self.registration.scope).href,badge:new URL('notification-badge.png',self.registration.scope).href,data:{id:p.id,userId:p.user_id,source:p.source||'campaign'},dir:'auto',timestamp:Date.now(),vibrate:[80,40,80]});if(epoch!==identityEpoch)for(const n of await self.registration.getNotifications())n.close();else await notifyWindows();})()));
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil((async()=>{const epoch=identityEpoch,data=event.notification.data||{},scope=new URL(self.registration.scope),combined=!!self.location?.href&&new URL(self.location.href).pathname.endsWith('/admin/push-sw.js'),entry=combined?new URL('../admin.html',scope):scope;if(!data.userId||!validId(data.id)||!['campaign','system'].includes(data.source)||!await sameRecipient(data.userId,epoch))return;const message={type:'OPEN_ADMIN_NOTIFICATIONS',id:data.id,source:data.source};const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});if(epoch!==identityEpoch)return;for(const client of clients){const url=new URL(client.url);if(url.origin===scope.origin&&(combined?url.pathname===entry.pathname:url.pathname.startsWith(scope.pathname))){client.postMessage(message);return client.focus();}}const url=new URL(entry.href);url.searchParams.set('notifications','1');url.searchParams.set('notice',data.id);url.searchParams.set('source',data.source);return self.clients.openWindow(url.href);})());});

async function notifyWindows(){const scope=new URL(self.registration.scope);for(const client of await self.clients.matchAll({type:'window',includeUncontrolled:false})){const url=new URL(client.url);if(url.origin===scope.origin&&url.pathname.startsWith(scope.pathname))client.postMessage({type:'MASARIFI_PUSH_RECEIVED'});}}
