/* Masarifi: measured per-user application data; read-only administrator view. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MasarifiAdminDataUsage=api;})(typeof window!=='undefined'?window:globalThis,function(root){
'use strict';
const ids=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fields={workspace:'workspace_snapshot_bytes',private:'private_snapshot_bytes',legacy:'legacy_snapshot_bytes',entries:'shared_entry_bytes',audit:'shared_audit_bytes',boxes:'own_box_bytes',family:'family_profile_bytes',profile:'profile_bytes',storage:'storage_bytes'};
function integer(value){if(value===null||value===undefined||value===''||typeof value==='boolean')throw Error('usage_unavailable');const n=Number(value);if(!Number.isSafeInteger(n)||n<0)throw Error('usage_unavailable');return n;}
function avatar(value){
 if(typeof value!=='string'||value.length>87410)return null;const match=/^data:image\/(jpeg|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);if(!match||match[2].length%4!==0)return null;
 try{const decode=root.atob||globalThis.atob;if(typeof decode!=='function')return null;const data=decode(match[2]);if(data.length>65536)return null;if(match[1]==='jpeg'&&data.length>=3&&data.charCodeAt(0)===255&&data.charCodeAt(1)===216&&data.charCodeAt(2)===255)return value;if(match[1]==='webp'&&data.length>=12&&data.slice(0,4)==='RIFF'&&data.slice(8,12)==='WEBP')return value;}catch{}return null;
}
function model(data){
 if(!data||data.measurement!=='logical_utf8_rows_plus_storage_metadata'||!Array.isArray(data.users)||typeof data.measured_at!=='string'||!Number.isFinite(Date.parse(data.measured_at)))throw Error('usage_unavailable');
 const totalBytes=integer(data.total_measured_bytes),totalUsers=integer(data.total_users),seen=new Set();
 const users=data.users.map(row=>{if(!row||!ids.test(row.user_id||'')||seen.has(row.user_id))throw Error('usage_unavailable');seen.add(row.user_id);const components=Object.fromEntries(Object.entries(fields).map(([key,field])=>[key,integer(row[field])]));const total=integer(row.total_bytes);if(total!==Object.values(components).reduce((sum,value)=>sum+value,0)||total>totalBytes)throw Error('usage_unavailable');return {id:row.user_id,name:String(row.display_name||row.email||row.user_id),avatar:avatar(row.avatar_data_url),totalBytes:total,components,objects:integer(row.storage_object_count),unknownObjects:integer(row.storage_unknown_size_count),percent:totalBytes>0?total/totalBytes*100:null};});
 if(users.length>totalUsers)throw Error('usage_unavailable');return {users,totalBytes,totalUsers,measuredAt:data.measured_at,unknownObjects:integer(data.total_storage_unknown_size_count),unattributedBytes:integer(data.unattributed_storage_bytes),unattributedObjects:integer(data.unattributed_storage_object_count)};
}
const words={
 ar:{title:'بيانات المستخدمين على الخادم',scope:'حصة كل مستخدم من إجمالي بيانات التطبيق المقاسة لجميع المستخدمين على الخادم',total:'إجمالي البيانات المقاسة',measured:'وقت القياس',note:'حجم منطقي للصفوف بصيغة UTF-8 وأحجام الملفات المعروفة. لا يشمل الفهارس أو النسخ الاحتياطية أو كامل استهلاك الاستضافة.',network:'نقل الشبكة: لم يُقَس. هذه النسبة ليست حصة من باقة أو فاتورة.',empty:'لا توجد حسابات ضمن هذا العرض.',unmeasured:'لا توجد بيانات مقاسة لحساب النسبة',workspace:'مساحة العمل',unattributed:'ملفات غير منسوبة لمستخدم؛ خارج النسبة',private:'المزامنة الخاصة',legacy:'المزامنة السابقة',entries:'الحركات المشتركة',audit:'سجل الحركات',boxes:'الصناديق',family:'الأسماء العائلية',profile:'الملف الشخصي',storage:'الملفات',unknown:'ملفات دون حجم معروف؛ الإجمالي جزئي',share:'من الإجمالي المقاس',previous:'السابق',next:'التالي',users:'مستخدمين',unnamed:'مستخدم'},
 en:{title:'User data on the server',scope:'Each user’s share of measured application data for all server users',total:'Total measured data',measured:'Measured at',note:'Logical UTF-8 row size and known file sizes. Excludes indexes, backups and total hosting consumption.',network:'Network traffic: not measured. This percentage is not a quota or bill.',empty:'No accounts in this view.',unmeasured:'No measured data for a percentage',workspace:'Workspace sync',unattributed:'Unattributed files; excluded from the percentage',private:'Private sync',legacy:'Legacy sync',entries:'Shared entries',audit:'Entry history',boxes:'Cashboxes',family:'Family names',profile:'Profile',storage:'Files',unknown:'Files without known size; total is partial',share:'of measured total',previous:'Previous',next:'Next',users:'users',unnamed:'User'},
 tr:{title:'Sunucudaki kullanıcı verileri',scope:'Her kullanıcının sunucudaki tüm kullanıcılar için ölçülen uygulama verilerindeki payı',total:'Ölçülen toplam veri',measured:'Ölçüm zamanı',note:'UTF-8 satırlarının mantıksal boyutu ve bilinen dosya boyutları. İndeksleri, yedekleri ve toplam barındırma tüketimini içermez.',network:'Ağ trafiği: ölçülmedi. Bu yüzde kota veya fatura değildir.',empty:'Bu görünümde hesap yok.',unmeasured:'Yüzde için ölçülen veri yok',workspace:'Çalışma alanı eşitleme',unattributed:'Kullanıcıya atanmamış dosyalar; yüzdeye dahil değil',private:'Özel eşitleme',legacy:'Önceki eşitleme',entries:'Paylaşılan hareketler',audit:'Hareket geçmişi',boxes:'Kasalar',family:'Aile adları',profile:'Profil',storage:'Dosyalar',unknown:'Boyutu bilinmeyen dosyalar; toplam kısmidir',share:'ölçülen toplamın',previous:'Önceki',next:'Sonraki',users:'kullanıcı',unnamed:'Kullanıcı'},
 fr:{title:'Données des utilisateurs sur le serveur',scope:'Part de chaque utilisateur dans les données mesurées de tous les utilisateurs du serveur',total:'Total des données mesurées',measured:'Mesuré le',note:'Taille logique des lignes UTF-8 et tailles de fichiers connues. Exclut les index, sauvegardes et consommation totale de l’hébergement.',network:'Trafic réseau : non mesuré. Ce pourcentage n’est ni un quota ni une facture.',empty:'Aucun compte dans cette vue.',unmeasured:'Aucune donnée mesurée pour un pourcentage',workspace:'Espace de travail',unattributed:'Fichiers non attribués ; exclus du pourcentage',private:'Synchronisation privée',legacy:'Ancienne synchronisation',entries:'Écritures partagées',audit:'Historique',boxes:'Caisses',family:'Noms de famille',profile:'Profil',storage:'Fichiers',unknown:'Fichiers de taille inconnue ; total partiel',share:'du total mesuré',previous:'Précédent',next:'Suivant',users:'utilisateurs',unnamed:'Utilisateur'}
};
function language(locale){return words[locale]||words.en;}
function bytes(value,locale){const n=Number(value);if(n===0)return '0 B';const power=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return new Intl.NumberFormat(locale,{maximumFractionDigits:power?2:0}).format(n/1024**power)+' '+['B','KiB','MiB','GiB','TiB'][power];}
function percentage(value,locale){return new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(value)+'%';}
function rowHTML(user,locale){const t=language(locale),percent=user.percent,initial=Array.from(user.name.trim())[0]||t.unnamed[0];return `<article class="data-usage-row" data-usage-user="${esc(user.id)}"><div class="data-usage-identity">${user.avatar?`<img class="data-usage-avatar" src="${esc(user.avatar)}" alt="" width="48" height="48" loading="lazy">`:`<span class="data-usage-avatar data-usage-initial" aria-hidden="true">${esc(initial)}</span>`}<div><h3>${esc(user.name)}</h3><bdi class="data-usage-id">${esc(user.id)}</bdi></div></div><div class="data-usage-amount"><strong>${esc(bytes(user.totalBytes,locale))}</strong><span>${percent===null?esc(t.unmeasured):esc(percentage(percent,locale)+' '+t.share)}</span></div><div class="data-usage-meter" ${percent===null?'aria-hidden="true"':`role="progressbar" aria-label="${esc(user.name+' · '+t.share)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent}" aria-valuetext="${esc(percentage(percent,locale))}"`}><span style="width:${percent===null?0:percent}%"></span></div><dl class="data-usage-components">${Object.entries(user.components).map(([key,value])=>`<div><dt>${esc(t[key])}</dt><dd>${esc(bytes(value,locale))}</dd></div>`).join('')}</dl>${user.unknownObjects?`<p class="data-usage-partial">${esc(user.unknownObjects+' · '+t.unknown)}</p>`:''}</article>`;}
function html(value,locale='ar',offset=0){const t=language(locale),date=new Date(value.measuredAt).toLocaleString(locale);return `<section class="data-usage-workspace" aria-labelledby="dataUsageTitle"><div class="panel data-usage-summary"><div><p class="eyebrow">MASARIFI / DATA</p><h2 id="dataUsageTitle">${esc(t.title)}</h2><p>${esc(t.scope)}</p></div><div class="data-usage-server-total"><span>${esc(t.total)}</span><strong>${esc(bytes(value.totalBytes,locale))}</strong></div><p class="hint">${esc(t.measured)} <time datetime="${esc(value.measuredAt)}">${esc(date)}</time></p><p class="hint">${esc(t.note)}</p><p class="hint">${esc(t.network)}</p>${value.unknownObjects?`<p class="data-usage-partial">${esc(value.unknownObjects+' · '+t.unknown)}</p>`:''}${value.unattributedObjects?`<p class="hint">${esc(t.unattributed)}: ${esc(bytes(value.unattributedBytes,locale))} (${value.unattributedObjects})</p>`:''}</div><div class="data-usage-list">${value.users.map(user=>rowHTML(user,locale)).join('')||`<p class="panel hint">${esc(t.empty)}</p>`}</div><div class="row pagination">${offset?`<button type="button" data-a="prev">${esc(t.previous)}</button>`:''}<span>${value.totalUsers?offset+1:0}–${offset+value.users.length} / ${value.totalUsers} ${esc(t.users)}</span>${offset+value.users.length<value.totalUsers?`<button type="button" data-a="next">${esc(t.next)}</button>`:''}</div></section>`;}
function render(screen,value,locale,offset){
 const markup=html(value,locale,offset),existing=screen.querySelector?.('.data-usage-workspace');
 if(!existing||!screen.ownerDocument?.createElement){screen.innerHTML=markup;return;}
 const fresh=screen.ownerDocument.createElement('div');fresh.innerHTML=markup;const next=fresh.firstElementChild,list=existing.querySelector('.data-usage-list'),nextList=next.querySelector('.data-usage-list'),old=new Map([...list.querySelectorAll('[data-usage-user]')].map(row=>[row.dataset.usageUser,row]));
 const scroll=screen.scrollTop,incoming=[...nextList.children];for(const replacement of incoming){const prior=old.get(replacement.dataset.usageUser);if(prior){const previousMeter=prior.querySelector('.data-usage-meter'),newMeter=replacement.querySelector('.data-usage-meter');if(previousMeter&&newMeter&&previousMeter.hasAttribute('role')&&newMeter.hasAttribute('role')){previousMeter.setAttribute('aria-valuenow',newMeter.getAttribute('aria-valuenow'));previousMeter.setAttribute('aria-valuetext',newMeter.getAttribute('aria-valuetext'));previousMeter.setAttribute('aria-label',newMeter.getAttribute('aria-label'));previousMeter.firstElementChild.style.width=newMeter.firstElementChild.style.width;newMeter.replaceWith(previousMeter);}old.delete(replacement.dataset.usageUser);prior.remove();}list.append(replacement);}
 for(const stale of [...list.children])if(!incoming.includes(stale))stale.remove();
 existing.querySelector('.data-usage-summary').replaceWith(next.querySelector('.data-usage-summary'));existing.querySelector('.pagination').replaceWith(next.querySelector('.pagination'));screen.scrollTop=scroll;
}
function request(bridge,options={},fetcher=root.fetch?.bind(root)){
 const offset=options.offset??0,limit=options.limit??100;
 if(!Number.isSafeInteger(offset)||offset<0||!Number.isSafeInteger(limit)||limit<1||limit>100||typeof fetcher!=='function')throw Error('invalid_request');
 return (async()=>{const pin=await bridge.session();if(!bridge.current(pin))throw Error('session_revoked');const config=bridge.connection(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
 try{const response=await fetcher(config.url.replace(/\/$/,'')+'/rest/v1/rpc/masarifi_admin_data_usage',{method:'POST',signal:controller.signal,headers:{apikey:config.key,Authorization:'Bearer '+pin.token,'Content-Type':'application/json'},body:JSON.stringify({p_limit:limit,p_offset:offset,p_search:''})});if(!bridge.current(pin))throw Error('session_revoked');let body;try{body=await response.json();}catch{body=null;}if(!bridge.current(pin))throw Error('session_revoked');if(!response.ok||!body?.ok){const known=['auth_required','admin_forbidden','session_revoked','device_revoked','invalid_request','network_timeout','offline'];const code=known.includes(body?.code)?body.code:response.status===401?'auth_required':response.status===403?'admin_forbidden':'usage_unavailable';if(['auth_required','admin_forbidden','session_revoked','device_revoked'].includes(code))bridge.revoke(pin,code);throw Error(code);}return model(body.data);}
 catch(error){if(!bridge.current(pin))throw Error('session_revoked');if(error.name==='AbortError')throw Error('network_timeout');throw error;}
 finally{clearTimeout(timer);}})();
}
const requests=new WeakMap(),snapshots=new WeakMap();
async function load(screen,options){const serial={},current=()=>requests.get(screen)===serial&&options.current();requests.set(screen,serial);try{const value=await request(options.bridge,{offset:options.offset??0,limit:100},options.fetcher);if(!current())return;render(screen,value,options.getLocale?.()||options.locale||'ar',options.offset??0);snapshots.set(screen,{value,offset:options.offset??0,current});}catch(error){if(current())throw error;}}
function localize(screen,locale){const snapshot=screen&&snapshots.get(screen);if(!snapshot||!snapshot.current())return false;render(screen,snapshot.value,locale,snapshot.offset);return true;}
return Object.freeze({model,avatar,bytes,html,render,request,load,localize});

});
